

DB_DIR ?= ./data/HHV1/db

# Main rules
.PHONY:%.vcf.gz.all %.bam.all
%.vcf.gz.all:%.vcf.gz
	$(MAKE) $*.vcf.gz.html $*.vcf.gz.docx $*.vcf.gz.csi
%.bam.all:%.bam
	$(MAKE) $*.bam.html $*.bam.bai
%.fasta.all:%.fasta
	$(MAKE) $*.asm.bam $*.asm.vcf.gz
	$(MAKE) $*.asm.bam.all $*.asm.vcf.gz.all


.PRECIOUS: %.asm.bam %.asm.vcf.gz %.filt.bam %.10k.bam %.bam.bai %.bcf %.bcf.txt

# BAM indexing and ONT read filtering rules
%.bam.bai:%.bam; samtools index "$<"
%.filt.bam:%.bam; ./bin/ontbam_filter.R --out "$@" "$<"
%.10k.bam:%.bam; ./bin/ontbam_subsample.R --out "$@" "$<"
%.vcf.gz.csi:%.vcf.gz; bcftools index "$<"


#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#
# 1a - Alignment and variant calling from a FASTA containing an assembly
#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#
%.asm.bam %.asm.vcf.gz %.asm.vcf.gz.csi:%.fasta
	./bin/asm2vcf.sh --ref-fasta="$(DB_DIR)/ref.fasta" --ref-gff="$(DB_DIR)/ref.gff" --asm-fasta="$<" --out-prefix="$*.asm"

#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#
# 1b - Variant calling from a BAM generated by minimap2 and containing aligned reads
#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#
%.vcf.gz %.vcf.gz.csi:%.bam %.bam.bai
	./bin/ontbam2vcf.sh --ref-gff="$(DB_DIR)/ref.gff" --ref-fasta="$(DB_DIR)/ref.fasta" --bam="$<" --out="$@"

#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#
# 4 - Generate reports
#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#
%.bam.html:%.bam %.bam.bai
	Rscript -e 'rmarkdown::render("notebooks/bam_report.Rmd",params=list(input_bam_file="$<"),knit_root_dir="$(PWD)",output_dir="$(@D)",output_file="$(@F)")'

%.vcf.gz.html:%.vcf.gz $(DB_DIR)/resistances.chk.xlsx
	Rscript -e 'rmarkdown::render("notebooks/vcf_report.Rmd",params=list(input_vcf_file="$<",input_db_dir="$(DB_DIR)",output_docx_report="$*.vcf.gz.docx"),knit_root_dir="$(PWD)",output_dir="$(@D)",output_file="$(@F)")'


#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#
# Clean rule
#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#
%/clean:
	rm -f \
	  '$*'/*.filt.bam \
	  '$*'/*.10k.bam \
    '$*'/*.10k.vcf.gz \
	  '$*'/*.asm.bam \
	  '$*'/*.asm.vcf.gz \
	  '$*'/*.bai \
    '$*'/*.vcf.gz.csi \
	  '$*'/*.vcf.gz.html \
	  '$*'/*.vcf.gz.docx \
	  '$*'/*.bam.html


